@Test1APBD_HostAddress = http://localhost:1433

GET {{Test1APBD_HostAddress}}/api/appointments/1
Accept: application/json

POST {{Test1APBD_HostAddress}}/api/appointments/create
Content-Type: application/json

{
"appointmentId": 10,
"patientId": 1,
"pwz": "PWZ5678",
"services": [
{
"serviceName": "Consultation",
"serviceFee": 110.00
},
{
"serviceName": "ECG",
"serviceFee": 70.00
}
]
}
